# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/se415011/sfarro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/se415011/sfarro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/se415011/sfarro/CMakeFiles /home/se415011/sfarro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/se415011/sfarro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfarro

# Build rule for target.
sfarro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfarro
.PHONY : sfarro

# fast build rule for target.
sfarro/fast:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/build
.PHONY : sfarro/fast

src/sfarro.o: src/sfarro.c.o
.PHONY : src/sfarro.o

# target to build an object file
src/sfarro.c.o:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/sfarro.c.o
.PHONY : src/sfarro.c.o

src/sfarro.i: src/sfarro.c.i
.PHONY : src/sfarro.i

# target to preprocess a source file
src/sfarro.c.i:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/sfarro.c.i
.PHONY : src/sfarro.c.i

src/sfarro.s: src/sfarro.c.s
.PHONY : src/sfarro.s

# target to generate assembly for a file
src/sfarro.c.s:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/sfarro.c.s
.PHONY : src/sfarro.c.s

src/vfs.o: src/vfs.c.o
.PHONY : src/vfs.o

# target to build an object file
src/vfs.c.o:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/vfs.c.o
.PHONY : src/vfs.c.o

src/vfs.i: src/vfs.c.i
.PHONY : src/vfs.i

# target to preprocess a source file
src/vfs.c.i:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/vfs.c.i
.PHONY : src/vfs.c.i

src/vfs.s: src/vfs.c.s
.PHONY : src/vfs.s

# target to generate assembly for a file
src/vfs.c.s:
	$(MAKE) -f CMakeFiles/sfarro.dir/build.make CMakeFiles/sfarro.dir/src/vfs.c.s
.PHONY : src/vfs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfarro"
	@echo "... src/sfarro.o"
	@echo "... src/sfarro.i"
	@echo "... src/sfarro.s"
	@echo "... src/vfs.o"
	@echo "... src/vfs.i"
	@echo "... src/vfs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

